# Generated by Django 3.2.4 on 2021-07-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
